# Generated by Django 3.2.7 on 2021-10-13 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
  
        
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
