# Generated by Django 3.2.7 on 2021-10-30 16:55

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211013_1704'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='project',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='genre',
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.ManyToManyField(to='account.Genre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Choose Status'), ('C', 'Completed'), ('P', 'Under production '), ('U', 'Upcoming')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[account.models.my_year_validator]),
        ),
       
    ]
