# Generated by Django 3.2.7 on 2021-12-30 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211030_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report_people',
            options={'ordering': ['-id']},
        ),
     
    
        migrations.AddField(
            model_name='user',
            name='get_notification',
            field=models.BooleanField(default=True),
        ),
  

    ]
