# Generated by Django 3.2.7 on 2022-01-11 09:21

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211230_1122'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='project_image'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(to='account.Language'),
        ),
    
     
    ]
