# Generated by Django 3.2.7 on 2022-01-14 14:18

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220114_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='user',
        ),
        migrations.AddField(
            model_name='highlight',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
       
        migrations.AlterField(
            model_name='highlight',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='account.project'),
        ),

    ]
