# Generated by Django 3.2.7 on 2022-01-17 14:16

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220114_1418'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='user',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),

    ]
