# Generated by Django 3.2.7 on 2022-07-06 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year_Of_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(blank=True, choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profession', models.CharField(max_length=256, null=True)),
                ('marital_status', models.CharField(max_length=256, null=True)),
                ('experience_in_movie_industry', models.CharField(max_length=256, null=True)),
                ('reference_if_any', models.CharField(max_length=256, null=True)),
                ('filim_title', models.CharField(max_length=256)),
                ('priority_of_submission', models.CharField(choices=[('S', 'Script'), ('V', 'Video')], default='S', max_length=1)),
                ('synopsis', models.CharField(max_length=100)),
                ('script', models.FileField(blank=True, upload_to='events/scripts')),
                ('script_password', models.CharField(blank=True, max_length=256)),
                ('video_link', models.URLField(blank=True)),
                ('video_password', models.CharField(blank=True, max_length=256)),
                ('subtitles', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('film_duration', models.PositiveIntegerField(null=True)),
                ('your_role_of_production', models.CharField(blank=True, max_length=256, null=True)),
                ('cinematographer', models.CharField(blank=True, max_length=256, null=True)),
                ('editor', models.CharField(blank=True, max_length=256, null=True)),
                ('music_director', models.CharField(blank=True, max_length=256, null=True)),
                ('writer', models.CharField(blank=True, max_length=256, null=True)),
                ('cast', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year_of_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.year_of_production')),
            ],
        ),
    ]
