# Generated by Django 3.2.7 on 2022-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
