# Generated by Django 3.2.7 on 2022-07-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_registration_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='filim_title',
            new_name='film_title',
        ),
    ]
