# Generated by Django 3.2.7 on 2022-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_filim_title_registration_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='submitted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
