# Generated by Django 3.2.7 on 2022-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_registration_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
