# Generated by Django 3.2.7 on 2022-07-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_registration_submitted_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-id',)},
        ),
    ]
