# Generated by Django 3.2.7 on 2022-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_registration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='director',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='film_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
