# Generated by Django 3.2.7 on 2022-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220707_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
