# Generated by Django 3.2.7 on 2022-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_registration_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
