# Generated by Django 3.2.7 on 2022-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20220708_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='film_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
