# Generated by Django 3.2.7 on 2022-07-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_email'),
        ('event', '0012_alter_registration_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sex',
        ),
        migrations.AlterField(
            model_name='registration',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.language'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='synopsis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
