# Generated by Django 3.2.7 on 2021-10-13 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='cannot_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='story_file',
            field=models.FileField(blank=True, null=True, upload_to='stories', validators=[project.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.post'),
        ),
    ]
