# Generated by Django 3.2.7 on 2022-01-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220111_0921'),
        ('project', '0002_auto_20211013_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='language',
        ),
        migrations.AddField(
            model_name='call',
            name='language',
            field=models.ManyToManyField(to='account.Language'),
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='language',
        ),
        migrations.AddField(
            model_name='pitch',
            name='language',
            field=models.ManyToManyField(to='account.Language'),
        ),
    ]
