# Generated by Django 3.2.7 on 2022-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220111_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_cover'),
        ),
    ]
